class CountryCodePicker {
  static List<Map<String, String>> countries = [
    {'name': 'Afghanistan', 'code': '+93'},
    {'name': 'Armenia', 'code': '+374'},
    {'name': 'Azerbaijan', 'code': '+994'},
    {'name': 'Bahrain', 'code': '+973'},
    {'name': 'Bangladesh', 'code': '+880'},
    {'name': 'Bhutan', 'code': '+975'},
    {'name': 'Brunei', 'code': '+673'},
    {'name': 'Cambodia', 'code': '+855'},
    {'name': 'China', 'code': '+86'},
    {'name': 'Georgia', 'code': '+995'},
    {'name': 'India', 'code': '+91'},
    {'name': 'Indonesia', 'code': '+62'},
    {'name': 'Iran', 'code': '+98'},
    {'name': 'Iraq', 'code': '+964'},
    {'name': 'Israel', 'code': '+972'},
    {'name': 'Japan', 'code': '+81'},
    {'name': 'Jordan', 'code': '+962'},
    {'name': 'Kazakhstan', 'code': '+7'},
    {'name': 'Kuwait', 'code': '+965'},
    {'name': 'Kyrgyzstan', 'code': '+996'},
    {'name': 'Laos', 'code': '+856'},
    {'name': 'Lebanon', 'code': '+961'},
    {'name': 'Malaysia', 'code': '+60'},
    {'name': 'Maldives', 'code': '+960'},
    {'name': 'Mongolia', 'code': '+976'},
    {'name': 'Myanmar', 'code': '+95'},
    {'name': 'Nepal', 'code': '+977'},
    {'name': 'North Korea', 'code': '+850'},
    {'name': 'Oman', 'code': '+968'},
    {'name': 'Pakistan', 'code': '+92'},
    {'name': 'Palestine', 'code': '+970'},
    {'name': 'Philippines', 'code': '+63'},
    {'name': 'Qatar', 'code': '+974'},
    {'name': 'Saudi Arabia', 'code': '+966'},
    {'name': 'Singapore', 'code': '+65'},
    {'name': 'South Korea', 'code': '+82'},
    {'name': 'Sri Lanka', 'code': '+94'},
    {'name': 'Syria', 'code': '+963'},
    {'name': 'Taiwan', 'code': '+886'},
    {'name': 'Tajikistan', 'code': '+992'},
    {'name': 'Thailand', 'code': '+66'},
    {'name': 'Timor-Leste', 'code': '+670'},
    {'name': 'Turkmenistan', 'code': '+993'},
    {'name': 'United Arab Emirates', 'code': '+971'},
    {'name': 'Uzbekistan', 'code': '+998'},
    {'name': 'Vietnam', 'code': '+84'},
    {'name': 'Yemen', 'code': '+967'},
  ];
}
